create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  name text not null,
  inserted_at timestamptz not null default now()
);

alter table public.todos enable row level security;

drop policy if exists "Users can read their own todos" on public.todos;
create policy "Users can read their own todos"
  on public.todos
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert their own todos" on public.todos;
create policy "Users can insert their own todos"
  on public.todos
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

grant select, insert on public.todos to authenticated;
